# This workflow builds the f4_npc_ai plugin whenever changes are pushed to the repository.
name: Build F4SE Plugin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # The build type for the plugin.
  BUILD_TYPE: Release

jobs:
  build:
    # IMPORTANT: F4SE requires the Windows toolchain (MSVC), so we must run on a Windows machine.
    runs-on: windows-latest

    steps:
      # 1. Checkout the source code of your forked repository.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure the project using CMake.
      #    - We explicitly use the "Visual Studio 17 2022" generator.
      #    - The -A x64 flag ensures we are building a 64-bit DLL.
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64

      # 3. Build the plugin.
      #    - We specify the target "f4_npc_ai" to ensure only our plugin and its direct dependencies are compiled.
      #    - The --config flag tells the build tool to use the Release configuration.
      - name: Build Plugin
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target f4_npc_ai

      # 4. Package the final DLL for release.
      #    - This creates the correct folder structure (F4SE/Plugins) that users need for installation.
      #    - It then zips this structure into an archive for easy downloading.
      - name: Package Artifact
        run: |
          mkdir -p dist/F4SE/Plugins
          copy ${{github.workspace}}/build/Plugins/${{env.BUILD_TYPE}}/f4_npc_ai.dll dist/F4SE/Plugins/f4_npc_ai.dll
          7z a ${{github.workspace}}/f4_npc_ai_plugin.zip ${{github.workspace}}/dist/*
        shell: cmd

      # 5. Upload the packaged zip file as a build artifact.
      #    - This makes the f4_npc_ai_plugin.zip file available for download on the GitHub Actions summary page for this run.
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: f4_npc_ai-plugin-release
          path: ${{github.workspace}}/f4_npc_ai_plugin.zip
